version: "3.8"

services:
  api:
    build:
      context: api
    ports:
      - 8000:8000
  db:
    image: postgres:14.3-alpine3.16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=HJFHSN2OFJFEC52UKV2CMNBBKQ

volumes:
  db-data:
